apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-project

# Resources live under base/ so paths are base/<file>
resources:
  - base/demo-project-namespace.yaml
  - base/pvc-dynamic-plugins.yaml
  - base/app-config.yaml
  - base/dynamic-plugins.yaml
  - base/user-entities.yaml
  - base/rbac.yaml
  - base/backstage-instance.yaml
