apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vote-application
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: vote-app-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: vote-app-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: vote-app
        server: "{{server}}"
      project: default
      sources:
        - path: application/vote-application
          repoURL: https://github.com/sureshgaikwad/gitops-catalog.git
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Validate=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: vote-app-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  numberOfClusters: 1

