apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-secret.yaml
  - app-config.yaml
  - user-entities.yaml
  - dynamic-plugins.yaml
  - backstage-instance.yaml
  - rbac.yaml

