apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-project

resources:
  - demo-project-namespace.yaml
  - auth-secret.yaml
  - app-config.yaml
  - dynamic-plugins.yaml
  - user-entities.yaml
  - rbac.yaml
  - backstage-instance.yaml
